keys:
- &mmertens age1rvcntlua0z49w6alfgh4kxc4fuwhfee4gqv9nkawmv8xl8277v4qpmcmq2
- &seshared age14lej52n0mvj9ms9ujk6yswxatfgvv8402v0azxtyx99rr6mswcfq5gqnlk
creation_rules:
- path_regex: .*\.sops\..*
  key_groups:
  - age:
    - *seshared
    - *mmertens