server_name: "matrix.local.tine-dev.de"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/etc/synapse/matrix.local.tine-dev.de.log.config"
media_store_path: /data/media_store
registration_shared_secret: "registration_shared_secret"
report_stats: false
macaroon_secret_key: "V.cDwl^pkUT47lRFQGi3^EgnJR5sxahuAlrGA=8VswmH;ok^.2"
form_secret: "874Ve~GUEtg~WV-22avVn~:~k.ezlbiuO#kq9#70t1UB-G,61="
signing_key_path: "/etc/synapse//matrix.local.tine-dev.de.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"
enable_registration: true
enable_registration_without_verification: true
password_config:
  policy:
    enabled: false