# this is a override file to add a broadcasthub container
services:
  web:
    volumes:
      - ./configs/broadcasthub/broadcasthub.inc.php:/etc/tine20/conf.d/broadcasthub.inc.php:ro
  broadcasthub-service:
    image: tinegroupware/broadcasthub:0.8-r2
    container_name: broadcasthub
    environment:
      REDIS_URL: redis://cache:6379
      REDIS_CHANNEL: broadcasthub
      AUTH_TIMEOUT: 5000
      WS_PORT: 80
      ENABLE_MULTITENANCY_MODE: false
      TINE20_JSON_API_URL: http://web/ # internally connect w.o. ssl as node doesn't have cert
#      TINE20_JSON_API_URL_PATTERN: (http://tine.local.tine-dev.de)|(http://tenant(1|2|3).my-domain.test)
      DEBUG_DEFAULT_LOGGING: "on"
      DEBUG_LOG_TO_FILE: "off"
      DEBUG_LOG_FILE: ../../stdout.log
      TEST_INTEGRATION_WS_URL: ws://broadcasthub:80
      TEST_E2E_WS_URL: ws://broadcasthub:80
    networks:
      - external_network
      - internal_network
    links:
      - traefik:tine.local.tine-dev.de
    labels:
      - traefik.enable=true
      - traefik.http.routers.broadcasthub.rule=Host(`broadcasthub.local.tine-dev.de`)
      - traefik.http.routers.broadcasthub.entrypoints=websecure
      - traefik.http.routers.broadcasthub.tls=true
      - traefik.http.services.broadcasthub.loadbalancer.server.port=80