# this is a override file to add a clamav container
version: '3'
services:
  clamav:
    image: tiredofit/clamav
    container_name: clamav
    environment:
      - ZABBIX_HOSTNAME=clamav
    volumes:
      # need to be created on the host
      - ./data/clamav:/data
      #- ./logs/clamav:/var/log/clamav
    networks:
      - internal_network
      - external_network
  web:
    volumes:
      - ./configs/clamav/clamav.inc.php:/etc/tine20/conf.d/clamav.inc.php:ro
      # install ubuntu package "clamav-testfiles" first
      # TODO only mount if existing?
      # - /usr/share/clamav-testfiles/:/usr/share/clamav-testfiles/:ro
