# this is a override file to add a ldap container
services:
  ldap:
    image: ghcr.io/tine-groupware/tine-dev/ldap:1.2.5-tine1
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
    command: --copy-service
    environment:
      LDAP_ORGANISATION: "Tine20 dev"
      LDAP_DOMAIN: "tine.test"
      LDAP_ADMIN_PASSWORD: "admin"
    networks:
      - internal_network

  web:
    environment:
      TINE20_ACCOUNTS: "backend:ldap,host:ldap\\://ldap,port:389,username:cn=admin\\,dc=tine\\,dc=test,password:admin,userDn:ou=users\\,dc=tine\\,dc=test,groupsDn:ou=groups\\,dc=tine\\,dc=test,defaultUserGroupName:Users,defaultAdminGroupName:Administrators"
      TINE20_AUTHENTICATION: "bindRequiresDn:1,backend:ldap,host:ldap\\://ldap,port:389,username:cn=admin\\,dc=tine\\,dc=test,password:admin,baseDn:ou=users\\,dc=tine\\,dc=test,accountFilterFormat:(&(objectClass=posixAccount)(uid=%s)),accountCanonicalForm:2"