services:
  web:
    links:
      - traefik:matrix.local.tine-dev.de
    volumes:
      - ./configs/matrix/matrix.inc.php:/etc/tine20/conf.d/matrix.inc.php:ro

  synapse:
    image: matrixdotorg/synapse:latest
    user: 991:991
    environment:
      SYNAPSE_CONFIG_PATH: /etc/synapse/homeserver.yaml
    volumes:
      - ./configs/matrix/synapse:/etc/synapse/
      - ./tine20/docs/operators/matrix/rest_auth_provider.py:/usr/local/lib/python3.12/site-packages/rest_auth_provider.py
      - synapse:/data
    networks:
      - internal_network
    links:
      - traefik:tine.local.tine-dev.de
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix.rule=Host(`matrix.local.tine-dev.de`)
      - traefik.http.routers.matrix.entrypoints=websecure
      - traefik.http.routers.matrix.tls=true
      - traefik.http.services.matrix.loadbalancer.server.port=8008

  element:
    image: vectorim/element-web:latest
    volumes:
      - ./configs/matrix/element-config.json:/app/config.json
    networks:
      - internal_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.element.rule=Host(`element.local.tine-dev.de`)
      - traefik.http.routers.element.entrypoints=websecure
      - traefik.http.routers.element.tls=true
      - traefik.http.services.element.loadbalancer.server.port=80
    healthcheck:
      test: [CMD, "true"]

volumes:
  synapse:
