services:
  web:
    links:
      - traefik:matrix.local.tine-dev.de
    volumes:
      - ./configs/matrix/matrix.inc.php:/etc/tine20/conf.d/matrix.inc.php:ro
  # after tine ins installed - start synapse
  # docker compose -f docker-compose.yml -f compose/matrix.yml up --detach
  # inti volume permissions
  # docker compose -f docker-compose.yml -f compose/matrix.yml run --user root --entrypoint /usr/bin/env synapse bash -c "chown 991:991 /data"
  # setup corporal user
  # docker compose -f docker-compose.yml -f compose/matrix.yml exec synapse register_new_matrix_user --config /etc/synapse/homeserver.yaml --admin --password=corporalpassword --user corporal
  synapse:
    image: matrixdotorg/synapse:v1.135.2
    user: 991:991
    environment:
      SYNAPSE_CONFIG_PATH: /etc/synapse/homeserver.yaml
    volumes:
      - ./configs/matrix/synapse:/etc/synapse/
      - ./tine20/docs/operators/matrix/rest_auth_provider.py:/usr/local/lib/python3.12/site-packages/rest_auth_provider.py
      - ./configs/matrix/synapse/shared_secret_authenticator.py:/usr/local/lib/python3.12/site-packages/shared_secret_authenticator.py
      - synapse:/data
    networks:
      - internal_network
    links:
      - traefik:tine.local.tine-dev.de
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix.rule=Host(`matrix.local.tine-dev.de`)
      - traefik.http.routers.matrix.entrypoints=websecure
      - traefik.http.routers.matrix.tls=true
      - traefik.http.services.matrix.loadbalancer.server.port=8008

  element:
    image: vectorim/element-web:latest
    volumes:
      - ./configs/matrix/element-config.json:/app/config.json
    networks:
      - internal_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.element.rule=Host(`element.local.tine-dev.de`)
      - traefik.http.routers.element.entrypoints=websecure
      - traefik.http.routers.element.tls=true
      - traefik.http.services.element.loadbalancer.server.port=80
    healthcheck:
      test: [CMD, "true"]

  matrix-wellknwon:
    image: nginx
    volumes:
      - ./configs/matrix/client.well-known.json:/usr/share/nginx/html/.well-known/matrix/client
      - ./configs/matrix/well-known.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrixwellknwon.rule=Host(`matrix.local.tine-dev.de`) && PathPrefix(`/.well-known/matrix`)
      - traefik.http.routers.matrixwellknwon.entrypoints=websecure
      - traefik.http.routers.matrixwellknwon.tls=true
      - traefik.http.services.matrixwellknwon.loadbalancer.server.port=80
    
  corporal:
    image: devture/matrix-corporal:3.1.2
    volumes:
      - ./configs/matrix/corporal.json:/etc/corporal/config.json
      - corporal:/data
    command:
      - /matrix-corporal
      - -config
      - /etc/corporal/config.json
    networks:
      - internal_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrixcorporal.rule=Host(`matrix.local.tine-dev.de`) && PathPrefix(`/_matrix/corporal/`)
      - traefik.http.routers.matrixcorporal.entrypoints=websecure
      - traefik.http.routers.matrixcorporal.tls=true
      - traefik.http.services.matrixcorporal.loadbalancer.server.port=41081

volumes:
  synapse:
  corporal:
